admin_site/urls.py
from django.urls import path
from admin_site import views
from django.conf.urls.static import static



app_name = 'admin_site'
urlpatterns = [
    path('', views.dashboard_admin, name='dashboard'),
    path('user-list/', views.user_list , name='user_list'),
    path('edit-user-list/<int:userid>/', views.edit_user_account, name='edit_user_account'),
    path('add-useraccount/', views.add_useraccount, name='add_useraccount'),
    path('update-user-list/<int:userid>/', views.update_user_account , name='update_user_account'),

    path('list-inquiry/', views.list_inquiry, name='list_inquiry'),
    path('list-reseller/', views.list_reseller, name='list_reseller'),
    path('edit-reseller/<int:id>/', views.edit_reseller, name='edit_reseller'),
    path('update-reseller/<int:id>/', views.update_reseller, name='update_reseller'),
    path('archive-reseller/<int:resellerid>/', views.archive_reseller, name='archive_reseller'),

    path('add_profile/', views.add_profile, name='add_profile'),
    path('update_profile/<int:profileid>', views.update_profile, name='update_profile'),

    path('My-profile/', views.my_profile, name='my_profile'),



    path('list-archive-reseller/', views.list_archive, name='list_archive'),
    path('retrieve-reseller/<int:id>/', views.retrieve_reseller, name='retrieve_reseller'),



    # path('send-email/', views.send_email, name='send_email'),
    path('send-email/<int:id>/', views.send_email, name='send_email'),
    path('send-email-reseller/<int:id>/', views.send_email_reseller, name='send_email_reseller'),    



    path('process/inquiry/', views.process_inquiry, name='process_inquiry'),

    #adding reseller 
    path('adding-reseller/', views.add_reseller, name='add_reseller'),

    path('product/', views.list_products, name='list_product'),
    path('view-product/<int:productid>/', views.view_product, name='view_product'),
    path('add-product/', views.add_product, name='add_product'),
    path('check-product/', views.settings_product_check, name='settings_product_check'),
    path('Process-product/', views.process_product, name='process_product'),
    path('edit-product/<int:productid>/', views.edit_product, name='edit_product'),
    path('update-product/<int:productid>/', views.update_product, name='update_product'),


    path('inventory/', views.inventory, name='inventory'),
    path('view-inventory/', views.view_inventory, name='view_inventory'),
   
    path('update-inventory/<int:productid>/', views.update_inventory, name='update_inventory'),

    path('pos/', views.pos ,name='pos'),
    path('pos-receipt/', views.pos_receipt ,name='pos_receipt'),
    path('pos-remove/', views.pos_removeall ,name='pos_removeall'),
    path('pos-receipt/', views.Click_receipt ,name='click_receipt'),
    
    path('pos/add-receipt/', views.pos_addreceipt ,name='add_receipt'),
    path('pos/receipt-process/', views.pos_receipt_process ,name='receipt_process'),

    path('minus-qty/<int:productid>/', views.minus_qty, name='minus_qty'),
    path('add-qty/<int:productid>/', views.add_qty ,name='add_qty'),

    path('pos/cancel/<int:productid>/', views.pos_cancel,name='pos_cancel'),


    path('pos/all-products/', views.all_products ,name='all_products'),
    path('cart/all-products/<int:productid>/', views.cart_products ,name='cart_products'),

    path('transaction-orders/pending', views.Transaction_orders, name='transaction_orders'),

# new status
    path('transaction-orders/in-process', views.in_process, name='in_process'),
    path('transaction-orders/in process', views.Transaction_in_process, name='transaction_in_process'),

    path('transaction-orders/process-out-for-delivery', views.delivery_process, name='delivery_process'),
    path('transaction-orders/out for shipping', views.Transaction_outshipping, name='transaction_outshipping'),

    path('transaction-orders/completed', views.Transaction_completed, name='transaction_completed'),
    path('transaction-orders/process-completed', views.completed_process, name='completed_process'),

    path('transaction-view/<int:id>/', views.transaction_view, name='transaction_view'),
    
    #search 
    path('search-reseller/', views.search_reseller, name='search_reseller'),
    path('search-archive-reseller/', views.search_archive, name='search_archive_reseller'),
    path('search-product/', views.search_product, name='search_product'),
    path('search-inventory/', views.search_inventory, name='search_inventory'),
    path('search-transaction/', views.search_transaction, name='search_transaction'),
    path('search/activity-log/', views.search_actlog, name='search_act-log'),
    path('search/activity-log-date/', views.search_date_actlog, name='search_date_actlog'),
    path('search/online-sales', views.search_online_sales, name='search_online_sales'),
    path('search/pos-sales', views.search_pos_sales, name='search_pos_sales'),

    #report
    path('reports/activity-log/', views.report_actlog, name='report_actlog'),
    path('reports/pos-sales/', views.report_pos_sales, name='report_pos_sales'),
    path('reports/online-sales/', views.report_online_sales, name='report_online_sales'),
    path('reports/users/', views.report_users, name='report_users'),
    path('reports/resellers/', views.report_res, name='report_res'),
    path('reports/product/', views.report_product, name='report_product'),
    path('reports/stocks/', views.report_stocks, name='report_stocks'),


    path('register/<int:inquiryid>/', views.register, name='register'),
    path('viewing-pic/valid-id/<int:id>/', views.viewpic_vid , name='viewingpic_vid'),	
    path('viewing-pic/business-permit/<int:id>/', views.viewpic_bpermit , name='viewingpic_bpermit'),	

    #settings profile 
    path('settings_profile/', views.settings_profile, name='settings_profile'),
    path('settings_password/', views.settings_password, name='settings_password'),

    #view
    path('settings_product/', views.settings_product, name='settings_product'),
    # path('settings_add/', views.settings_addproduct, name='settings_addproduct'),

    #add 	
    path('add-category/', views.settings_addcategory , name='settings_addcategory'),	
    path('add-unit/', views.settings_addunit , name='settings_addunit'),	
    path('add-flavor/', views.settings_addflavor , name='settings_addflavor'),

    #remove
    # path('remove-settings_product/<int:id>/', views.settings_remove, name='settings_remove'),
    path('remove/Product-category/<int:id>/', views.remove_category , name='remove_category'),	
    path('remove/Product-unit/<int:id>/', views.remove_unit , name='remove_unit'),	
    path('remove/Product-flavor/<int:id>/', views.remove_flavor , name='remove_flavor'),

    #return products	
    # path('Return/Product/', views.return_product, name='return_product'),

    path('unreturned/Product/', views.unreturned_product, name='unreturned_product'),
    path('returned/Product/', views.returned_product, name='returned_product'),
    path('returned/completed/<int:id>/', views.returned_completed, name='returned_completed'),
    path('view-unreturned/<int:id>/', views.view_unreturned, name='view_unreturned'),
    path('view-returned/<int:id>/', views.view_unreturned, name='view_unreturned'),


    path('Add/Return-Product/', views.add_returnproduct , name='add_returnproduct'),
    path('edit/Return-Product/<int:id>/', views.edit_returnproduct , name='edit_returnproduct'),	
    path('update/Return-Product/<int:id>/', views.update_returnproduct , name='update_returnproduct'),
    

    path('support/', views.support, name='support'),
   
#    settings for visitor's page
    path('settings_content/', views.settings_page, name='settings_page'),

]

rider_site/urls.py
from django.urls import path
from rider_site import views

app_name = 'rider_site'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    # path('orders-reseller', views.deliver_orders, name='deliver_orders'),
    path('orders-completed/<int:orderid>/', views.orders_completed, name='orders_completed'),
    path('transaction-orders/process-completed', views.completed_process, name='completed_process'),


    path('report-deliver/', views.report_deliver, name='report_deliver'),

    path('orders/', views.transaction_orders, name='transaction_orders'),
    path('transaction-view/<int:id>/', views.transaction_view, name='transaction_view'),
   
]

scoops4u_capstone/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('user-site/', include('admin_site.urls')),
    path('reseller-site/', include('reseller_site.urls')),
    path('staff-site/', include('staff_site.urls')),
    path('rider-site/', include('rider_site.urls')),
]

urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rider_site/models.py
from django.db import models

# Create your models here.

    

rider_site/views.py
from django.shortcuts import render, redirect
from admin_site.models import *
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Q


# Create your views here.
def dashboard(request):
    list_pending = Transaction.objects.filter(transaction_orderstatus = "Out for Delivery").count()
    list_complete = Transaction.objects.filter(transaction_orderstatus = "Completed").count()
    list_profile = Profile.objects.filter(list_user = request.user)
    current_profile = Profile.objects.filter(list_user = request.user)

    context ={
        'list_pending':list_pending,
        'list_complete':list_complete,
        'sidebar' : 'riderdashboard',
        'list_profile': list_profile,
        'current_profile':current_profile,
    }
    return render(request, 'rider_site/dashboard/index.html', context)

# @login_required(login_url='landing_page:login')
# def deliver_orders(request):
#     status = "Out for Shipping"
#     list_transaction = Transaction.objects.filter(transaction_orderstatus = status)
#     context = {
#         'list_transaction': list_transaction
#     }
#     return render(request, 'rider_site/deliver_orders/deliver_orders.html', context)

@login_required(login_url='landing_page:login')
def orders_completed(request, orderid):
    if request.method == "POST":
        transaction = Transaction.objects.get(id = orderid)
        now = datetime.now()
        status = "Completed"
        activity = "Delivered"
        transaction.transaction_delivered = now
        transaction.transaction_orderstatus = status
        transaction.save()
        
        NewActLog = Activity_log()
        NewActLog.user_name = request.user
        NewActLog.activity = activity 
        NewActLog.role = request.user.role
        NewActLog.date_time = now
        NewActLog.save()


        messages.success(request, ("Successfully Delivered"))
        return redirect('rider_site:transaction_orders')


@login_required(login_url='landing_page:login') 
def transaction_orders(request):
    status = "Out for Delivery"
    current_profile = Profile.objects.filter(list_user = request.user)
    list_profile = Profile.objects.filter(list_user = request.user)
    list_transaction = Transaction.objects.filter(Q(transaction_orderstatus = status) & Q(transaction_doption = "delivery")).order_by('-id')
    context = {
        'list_transaction':list_transaction,
        'sidebar' : 'riderorders',
        'list_profile': list_profile,
        'current_profile':current_profile,
    }
    return render(request, 'rider_site/orders/index.html', context)

@login_required(login_url='landing_page:login') 
def transaction_view(request,id):
    if request.method == "GET":
        transaction = Transaction.objects.get(id = id)

        transaction_no = transaction.transaction_no
        list_orderitem = OrderItem.objects.filter(OrderItem_transactionNo = transaction_no).order_by('-id')

        list_total = OrderItem.objects.filter(OrderItem_transactionNo = transaction_no).all().aggregate(data=Sum('OrderItem_amount'))

        context = {
            'list_orderitem':list_orderitem,
            'list_total':list_total,
            'list_transaction':transaction
        }
        
    return render(request, 'rider_site/orders/view_orders.html', context)

@login_required(login_url='landing_page:login')
def completed_process(request):
    if request.method == "POST":
        transaction_no = request.POST['transaction_no']
        now = datetime.now()
        transaction = Transaction.objects.get(transaction_no = transaction_no)
        transaction.transaction_orderstatus = "Completed"
        transaction.transaction_delivered = now
        transaction.save()

        activity = "Delivered"
        NewActLog = Activity_log()
        NewActLog.user_name = request.user
        NewActLog.activity = activity 
        NewActLog.role = request.user.role
        NewActLog.date_time = now
        NewActLog.save()
        messages.success(request,("Successfully Delivered"))
        return redirect('rider_site:transaction_orders')



@login_required(login_url='landing_page:login')
def report_deliver(request):
    list_profile = Profile.objects.filter(list_user = request.user)
    list_transaction = Transaction.objects.filter(transaction_orderstatus = "Completed").order_by('-id')
    current_profile = Profile.objects.filter(list_user = request.user)
    context = {
        'list_transaction':list_transaction,
        'sidebar' : 'riderreport',
        'list_profile': list_profile,
        'current_profile':current_profile,
    }
    return render(request, 'rider_site/report/index.html',context)

templates/rider_site/orders/index.html
{% extends 'admin_site/base.html' %}

{% block title %}
    DELIVERY
{% endblock title %}


{% block content %}
{% load humanize %}

<main id="main" class="main mt-5">
    <div class="pagetitle">
        <h1>Delivery</h1>
        <nav>
            {% if user.role == "delivery_staff"%}
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'rider_site:dashboard'%}">Home</a></li>
                <!-- <li class="breadcrumb-item">Inventory</li> -->
                <li class="breadcrumb-item active">Delivery</li>
            </ol>
            {% endif %}
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        {% for message in messages %}
        <p class="alert alert-success mt-3">{{ message }}</p>
        {% endfor %}

        <div class="empty-screenOrDel d-none">
            <img src="../../../../static/img/nopackages.svg" alt="">
            <h5>No Packages to Deliver</h5>
            <p>There are currently no packages to deliver to resellers.</p>
        </div>

        <div id="ordersDelID" class="row d-none">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body mt-3">
                        <div class="add-product order-d mb-4">
                            <h5 class="card-title feature">Orders</h5>
                            <div class="show-entries">
                                <div id="showEntries"></div>
                            </div>
                            <!-- <div class="modal-add-prod">
                                <a href="{% url 'admin_site:add_product' %}" class="btn btn-add-product" data-bs-toggle="modal" data-bs-target="#addProductModal"><i class="ri-add-line align-middle me-2 text-end" style="font-size:17px; font-weight: 500;"></i><span class="align-middle pe-1">Add a New Product</span></a>
                            </div> -->
                            <form class="search-tab" action="" method="GET"  class="text-end px-4">
                                {% csrf_token %}
                                <input type="text" id="tableM" class="form-control p-2 ps-3" name="search" placeholder="Search">
                                <button class="btn btn-search btn-sm nope" type="submit"><i class="ri-search-line"></i></button>
                            </form>  
                        </div>

                        {% if list_transaction %} 
                            <div class="table-responsive">
                                <!-- <table id="tableOrderDe" class="table table-hover" > -->
                                <table id="tableOrderDe" class="table table-hover d-none" >
                                    <thead>
                                        <tr class="align-middle">
                                            <th scope="col">#</th>
                                            <th scope="col">Order Date</th>
                                            <th scope="col">Transaction Number</th>
                                            <th scope="col">Total Price</th>
                                            <th scope="col" class="sort-no">Status</th>
                                            <th scope="col" class="sort-no">Action</th>
                                        </tr>
                                    </thead>

                                    <tbody id="tableRow">
                                        {% for list in list_transaction %}
                                        <tr class="align-middle">
                                            <td class="num-row"></td>
                                            <td>{{ list.created_at}}</td>
                                            <td>{{ list.transaction_no }}</td>
                                            <td>Php {{ list.transaction_totalprice|floatformat:2|intcomma}}</td>
                                            <td><span class="badge badge-stat-res rounded-pill bg-out">{{ list.transaction_orderstatus }}</span></td>
                                            <td class="modal-view-order">
                                                <a href="{% url 'rider_site:transaction_view' list.id %}" 
                                                    data-bs-toggle="modal" 
                                                    data-bs-target="#viewOrderModal" 
                                                    class="text-decoration-none">
                                                    <i class="ri-eye-fill btn-edit"></i>
                                                </a>
                                            </td>
                                            <!-- <form action="{% url 'admin_site:transaction_view' list.id  %}" method="GET" >
                                                {% csrf_token %}
                                                    
                                                    <td><input type="submit" class="btn btn-light" value="View"></td>
                                            </form> -->
                                
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        {% endif %} 
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- VIEW ORDER -->
    <div class="modal fade border-0"  id="viewOrderModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-fullscreen modal-dialog-scrollable">
            <div class="modal-content border-0 p-4">
                
            </div>
        </div>
    </div>
</main>

<script>
    // tables for transactions
   var tableOrDe = $('#tableOrderDe').DataTable({
       "fnDrawCallback": function(oSettings) {
           if (oSettings._iDisplayLength > oSettings.fnRecordsDisplay()) {
               $(oSettings.nTableWrapper).find('.dataTables_paginate').hide();
           } else {
               $(oSettings.nTableWrapper).find('.dataTables_paginate').show();
           }
       },
       
       "lengthChange": true,

       initComplete: (settings, json)=>{
           $('.dataTables_length').appendTo('#showEntries');
       },

       "oLanguage": {
           // &nbsp; is a blank text ---- used for spacing
           "sLengthMenu": "_MENU_ &nbsp;&nbsp;Entries per page",
           "oPaginate": {
               sNext: '<i class="ri-arrow-right-s-line"></i>',
               sPrevious: '<i class="ri-arrow-left-s-line"></i>',
               // sFirst: '<i class="ri-arrow-left-s-fill"></i>',
               // sLast: '<i class="ri-arrow-right-s-fill"></i>'
           }
       },

       columnDefs: [
           {
               searchable: false,
               orderable: false,
               targets: 0, 
           },
       ],
       // order: [[1, 'asc']],
       order: [] 
   });

   // for row numbers
   tableOrDe.on('order.dt search.dt', function () {
       let i = 1;

       tableOrDe.cells(null, 0, { search: 'applied', order: 'applied' }).every(function (cell) {
           this.data(i++);
       });
   }).draw();

   // for most tables search bar
   $('#tableM').keyup(function(){
       tableOrDe.search($(this).val()).draw();
   });  

   if ($('#tableOrderDe').DataTable().rows().count() === 0) {
        $("#tableOrderDe").addClass("d-none");
        $("#ordersDelID").addClass("d-none");
        $(".empty-screenOrDel").removeClass("d-none");
    } else {
        $("#tableOrderDe").removeClass("d-none");
        $("#ordersDelID").removeClass("d-none");
        $(".empty-screenOrDel").addClass("d-none");
    }

</script>
{% endblock %}