admin_site/urls.py
from django.urls import path
from admin_site import views
from django.conf.urls.static import static



app_name = 'admin_site'
urlpatterns = [
    path('', views.dashboard_admin, name='dashboard'),
    path('user-list/', views.user_list , name='user_list'),
    path('edit-user-list/<int:userid>/', views.edit_user_account, name='edit_user_account'),
    path('add-useraccount/', views.add_useraccount, name='add_useraccount'),
    path('update-user-list/<int:userid>/', views.update_user_account , name='update_user_account'),

    path('list-inquiry/', views.list_inquiry, name='list_inquiry'),
    path('list-reseller/', views.list_reseller, name='list_reseller'),
    path('edit-reseller/<int:id>/', views.edit_reseller, name='edit_reseller'),
    path('update-reseller/<int:id>/', views.update_reseller, name='update_reseller'),
    path('archive-reseller/<int:resellerid>/', views.archive_reseller, name='archive_reseller'),

    path('add_profile/', views.add_profile, name='add_profile'),
    path('update_profile/<int:profileid>', views.update_profile, name='update_profile'),

    path('My-profile/', views.my_profile, name='my_profile'),



    path('list-archive-reseller/', views.list_archive, name='list_archive'),
    path('retrieve-reseller/<int:id>/', views.retrieve_reseller, name='retrieve_reseller'),



    # path('send-email/', views.send_email, name='send_email'),
    path('send-email/<int:id>/', views.send_email, name='send_email'),
    path('send-email-reseller/<int:id>/', views.send_email_reseller, name='send_email_reseller'),    



    path('process/inquiry/', views.process_inquiry, name='process_inquiry'),

    #adding reseller 
    path('adding-reseller/', views.add_reseller, name='add_reseller'),

    path('product/', views.list_products, name='list_product'),
    path('view-product/<int:productid>/', views.view_product, name='view_product'),
    path('add-product/', views.add_product, name='add_product'),
    path('check-product/', views.settings_product_check, name='settings_product_check'),
    path('Process-product/', views.process_product, name='process_product'),
    path('edit-product/<int:productid>/', views.edit_product, name='edit_product'),
    path('update-product/<int:productid>/', views.update_product, name='update_product'),


    path('inventory/', views.inventory, name='inventory'),
    path('view-inventory/', views.view_inventory, name='view_inventory'),
   
    path('update-inventory/<int:productid>/', views.update_inventory, name='update_inventory'),

    path('pos/', views.pos ,name='pos'),
    path('pos-receipt/', views.pos_receipt ,name='pos_receipt'),
    path('pos-remove/', views.pos_removeall ,name='pos_removeall'),
    path('pos-receipt/', views.Click_receipt ,name='click_receipt'),
    
    path('pos/add-receipt/', views.pos_addreceipt ,name='add_receipt'),
    path('pos/receipt-process/', views.pos_receipt_process ,name='receipt_process'),

    path('minus-qty/<int:productid>/', views.minus_qty, name='minus_qty'),
    path('add-qty/<int:productid>/', views.add_qty ,name='add_qty'),

    path('pos/cancel/<int:productid>/', views.pos_cancel,name='pos_cancel'),


    path('pos/all-products/', views.all_products ,name='all_products'),
    path('cart/all-products/<int:productid>/', views.cart_products ,name='cart_products'),

    path('transaction-orders/pending', views.Transaction_orders, name='transaction_orders'),

# new status
    path('transaction-orders/in-process', views.in_process, name='in_process'),
    path('transaction-orders/in process', views.Transaction_in_process, name='transaction_in_process'),

    path('transaction-orders/process-out-for-delivery', views.delivery_process, name='delivery_process'),
    path('transaction-orders/out for shipping', views.Transaction_outshipping, name='transaction_outshipping'),

    path('transaction-orders/completed', views.Transaction_completed, name='transaction_completed'),
    path('transaction-orders/process-completed', views.completed_process, name='completed_process'),

    path('transaction-view/<int:id>/', views.transaction_view, name='transaction_view'),
    
    #search 
    path('search-reseller/', views.search_reseller, name='search_reseller'),
    path('search-archive-reseller/', views.search_archive, name='search_archive_reseller'),
    path('search-product/', views.search_product, name='search_product'),
    path('search-inventory/', views.search_inventory, name='search_inventory'),
    path('search-transaction/', views.search_transaction, name='search_transaction'),
    path('search/activity-log/', views.search_actlog, name='search_act-log'),
    path('search/activity-log-date/', views.search_date_actlog, name='search_date_actlog'),
    path('search/online-sales', views.search_online_sales, name='search_online_sales'),
    path('search/pos-sales', views.search_pos_sales, name='search_pos_sales'),

    #report
    path('reports/activity-log/', views.report_actlog, name='report_actlog'),
    path('reports/pos-sales/', views.report_pos_sales, name='report_pos_sales'),
    path('reports/online-sales/', views.report_online_sales, name='report_online_sales'),
    path('reports/users/', views.report_users, name='report_users'),
    path('reports/resellers/', views.report_res, name='report_res'),
    path('reports/product/', views.report_product, name='report_product'),
    path('reports/stocks/', views.report_stocks, name='report_stocks'),


    path('register/<int:inquiryid>/', views.register, name='register'),
    path('viewing-pic/valid-id/<int:id>/', views.viewpic_vid , name='viewingpic_vid'),	
    path('viewing-pic/business-permit/<int:id>/', views.viewpic_bpermit , name='viewingpic_bpermit'),	

    #settings profile 
    path('settings_profile/', views.settings_profile, name='settings_profile'),
    path('settings_password/', views.settings_password, name='settings_password'),

    #view
    path('settings_product/', views.settings_product, name='settings_product'),
    # path('settings_add/', views.settings_addproduct, name='settings_addproduct'),

    #add 	
    path('add-category/', views.settings_addcategory , name='settings_addcategory'),	
    path('add-unit/', views.settings_addunit , name='settings_addunit'),	
    path('add-flavor/', views.settings_addflavor , name='settings_addflavor'),

    #remove
    # path('remove-settings_product/<int:id>/', views.settings_remove, name='settings_remove'),
    path('remove/Product-category/<int:id>/', views.remove_category , name='remove_category'),	
    path('remove/Product-unit/<int:id>/', views.remove_unit , name='remove_unit'),	
    path('remove/Product-flavor/<int:id>/', views.remove_flavor , name='remove_flavor'),

    #return products	
    # path('Return/Product/', views.return_product, name='return_product'),

    path('unreturned/Product/', views.unreturned_product, name='unreturned_product'),
    path('returned/Product/', views.returned_product, name='returned_product'),
    path('returned/completed/<int:id>/', views.returned_completed, name='returned_completed'),
    path('view-unreturned/<int:id>/', views.view_unreturned, name='view_unreturned'),
    path('view-returned/<int:id>/', views.view_unreturned, name='view_unreturned'),


    path('Add/Return-Product/', views.add_returnproduct , name='add_returnproduct'),
    path('edit/Return-Product/<int:id>/', views.edit_returnproduct , name='edit_returnproduct'),	
    path('update/Return-Product/<int:id>/', views.update_returnproduct , name='update_returnproduct'),
    

    path('support/', views.support, name='support'),
   
#    settings for visitor's page
    path('settings_content/', views.settings_page, name='settings_page'),

]

scoops4u_capstone/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('user-site/', include('admin_site.urls')),
    path('reseller-site/', include('reseller_site.urls')),
    path('staff-site/', include('staff_site.urls')),
    path('rider-site/', include('rider_site.urls')),
]

urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admin_site/profile/backup-myprofile.html
<div class="col-lg-8">
    <div class="card info-card profile-info-card">
            <div class="card-body label-profile-body dash mt-3 py-3 mb-3">
                <div class="col-lg-12 ps-5">
                    <div class="row">
                        <!-- EMAIL -->
                        <div class="col-lg-6">
                            <label class="label-profile" for="">Email</label>
                        </div>
                        <div class="col-lg-6">
                            <label class="label-desc" id="desc-profile" for="">{{list.profile_email}}</label>
                        </div>

                        <!-- USERNAME -->
                        <div class="col-lg-6">
                            <label class="label-profile" for="">Username</label>
                        </div>
                        <div class="col-lg-6">
                            <label class="label-desc" for="">{{list.list_user}}</label>
                        </div>

                        <!-- PHONE NUMBER -->
                        <div class="col-lg-6">
                            <label class="label-profile" for="">Phone Number</label>
                        </div>
                        <div class="col-lg-6">
                            <label class="label-desc" for="">0{{list.profile_cnumber}}</label>
                        </div>

                        <!-- PHONE NUMBER -->
                        <div class="col-lg-6">
                            <label class="label-profile" for="">Address</label>
                        </div>
                        <div class="col-lg-6">
                            <label class="label-desc" for="">{{list.profile_address}}</label>
                        </div>
                    </div>
                    
                </div>
            </div>
    </div>
</div>

templates/admin_site/profile/change_pass.html
{% load static %}

<div class="modal-header border-0">
    <h1 class="modal-title" id="exampleModalLabel">Change Password</h1>
    <button type="button" class="ri-close-fill" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<form  method="POST">
    {% csrf_token %}

    <div class="modal-body pt-2 mt-0">
        <div class="row d-flex-justify-content-center align-items-center">
            <div class="col-lg-12">
                <div class="row d-flex flex-column justify-content-center align-items-center"">
                    <div class="col-lg-12 new-ps">
                        <!-- <div class="row">
                            <div class="col-lg-6">

                            </div>
                            <span>{{ form.current_password }}</span>
                            <span>{{ form.new_password }}</span>
                        </div> -->

                        <div class="row d-flex justify-content-center align-items-center">
                            <div class="col-lg-5">
                                <label for="">Current Password</label>
                            </div>
                            <div class="col-lg-7">
                                <span>{{ form.current_password }}</span>
                                <!-- <input type="text" class="form-control" id="" aria-describedby="" required> -->
                            </div>
                        </div>

                        <div class="row d-flex justify-content-center align-items-center">
                            <div class="col-lg-5">
                                <label for="">New Password</label>
                            </div>
                            <div class="col-lg-7">
                                <span>{{ form.new_password }}</span>
                                <!-- <input type="text" class="form-control" id="" aria-describedby="" required> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer border-0">
        <!-- <button type="submit" class="btn btn-primary" value="Add Product"><i class="ri-check-fill"></i>Add Product</button> -->
        <button type="submit" id="submit" name="submit" class="btn btn-primary me-2"><i class="ri-arrow-up-line align-middle me-2 text-end" style="font-size:17px;"></i><span class="align-middle pe-1">Update</span></button>
        <a href="{% url 'admin_site:my_profile' %}" type="submit" id="close-modal" class="btn btn-secondary" data-bs-dismiss="modal" style="font-size: 15px; padding: 5px 13px;"><i class="ri-close-line align-middle me-2 text-end" style="font-size:17px;"></i><span class="align-middle pe-1">Cancel</span></a>
        <!-- <button type="submit" id="close-modal" class="btn btn-secondary" data-bs-dismiss="modal"><i class="ri-close-line align-middle me-2 text-end" style="font-size:17px;"></i><span class="align-middle pe-1">Cancel</span></button> -->
    </div>
</form>

templates/admin_site/profile/settings_profile.html
{% load static %}

<div class="modal-header border-0">
    <h1 class="modal-title" id="exampleModalLabel">Edit Profile</h1>
    <button type="button" class="ri-close-fill" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

{% if list_profile %}
{% for list in list_profile %}
<form action="{% url 'admin_site:update_profile' list.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="modal-body pt-2 mt-0">
        <div class="row d-flex-justify-content-center align-items-center text-center">
                <div class="col-lg-5"> 
                    <div class="row">
                        <div class="col-lg-12 edit-profile ">
                            <div class="profile-pic-ed ">
                                <!-- <img id="output" src="/media/{{ list.profile_pic}}" alt="Profile-pic" class="image-cropper"> -->
                                {% if list.profile_pic %}
                                <img id="output" src="/media/{{ list.profile_pic}}" alt="Profile-pic" class="image-cropper">
                                {% else %}
                                <img id="output" src="{% static 'img/default_profile.jpg' %}" alt="Profile-pic" class="image-cropper">
                                {% endif %}
                            </div>
                            
                            <!-- <input type="file"  name="profile_pic" class="mt-3" > -->
                        </div>
                        
                        <div class="col-lg-12 mt-3 edit-file">
                            <label for="file-upload" class="btn btn-print custom-file-upload me-2">
                                <i class="ri-upload-2-line"></i>
                            </label>
                            <input id="file-upload"  name="profile_pic" type="file" onchange="document.getElementById('output').src = window.URL.createObjectURL(this.files[0])"/>
                            <!-- <button class="btn btn-trash-pic"><i class="ri-delete-bin-line"></i></button> -->
                        </div>
                    </div>
                    
                </div>
            

            <div class="col-lg-3">
                <div class="first-input">
                    <label for="">First Name</label>
                    <input type="text"  name="first" class="form-control" value="{{ list.profile_fname}}" required>
                    
                    <label for="">Middle Name</label>
                    <input type="text"  name="middle" class="form-control" value="{{ list.profile_mname}}">
                    
                    <label for="">Last Name</label>
                    <input type="text"  name="last" class="form-control" value="{{ list.profile_lname}}" required>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="first-input">
                    <label for="">Contact No</label>
                    <input type="number"  name="contact_no" class="form-control" min="0" value="{{ list.profile_cnumber}}" 
                    maxlength="11" 
                    oninput="this.value=this.value.slice(0,this.maxLength)"
                    required>
                    
                    <label for="">Address</label>
                    <input type="text"  name="address" class="form-control"value="{{ list.profile_address}}" required>
                    
                    <label for="">Email Address</label>
                    <input type="text"  name="email" class="form-control" value="{{ list.profile_email}}" required>
                    <!-- <br> -->
                    <!-- <input type="submit"  class="btn btn-dark"  value="Update" required> -->
                </div>
                
                <!-- <button type="submit"  class="btn btn-profile-up">Update</button> -->
            </div>
        </div>
    </div>

    <div class="modal-footer border-0">
        <!-- <button type="submit" class="btn btn-primary" value="Add Product"><i class="ri-check-fill"></i>Add Product</button> -->
        <button type="submit" id="submit" name="submit" class="btn btn-primary me-2"><i class="ri-arrow-up-line align-middle me-2 text-end" style="font-size:17px;"></i><span class="align-middle pe-1">Update</span></button>
        <a href="{% url 'admin_site:my_profile' %}" type="submit" id="close-modal" class="btn btn-secondary" data-bs-dismiss="modal" style="font-size: 15px; padding: 5px 13px;"><i class="ri-close-line align-middle me-2 text-end" style="font-size:17px;"></i><span class="align-middle pe-1">Cancel</span></a>
        <!-- <button type="submit" id="close-modal" class="btn btn-secondary" data-bs-dismiss="modal"><i class="ri-close-line align-middle me-2 text-end" style="font-size:17px;"></i><span class="align-middle pe-1">Cancel</span></button> -->
    </div>
</form>
{% endfor %}
{% else %}
<form action="{% url 'admin_site:add_profile' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="modal-body pt-2 mt-0">
        <div class="row d-flex-justify-content-center align-items-center text-center">

            <div class="col-lg-5"> 
                <div class="row">
                    <div class="col-lg-12 edit-profile ">
                        <div class="profile-pic-ed ">
                            <!-- <img id="output" src="/media/{{ list.profile_pic}}" alt="Profile-pic" class="image-cropper">
                            <img src="{% if list.profile_pic %}{{ list.profile_pic.url }}{% else %}{% static 'img/default_profile.jpg' %}{% endif %}" alt="Profile-pic" class="image-cropper"> -->

                            {% if list.profile_pic %}
                            <img id="output" src="/media/{{ list.profile_pic}}" alt="Profile-pic" class="image-cropper">
                            {% else %}
                            <img id="output" src="{% static 'img/default_profile.jpg' %}" alt="Profile-pic" class="image-cropper">
                            {% endif %}
                        </div>
                        
                        <!-- <input type="file"  name="profile_pic" class="mt-3" > -->
                    </div>
                    
                    <div class="col-lg-12 mt-3 edit-file">
                        <label for="file-upload" class="btn btn-print custom-file-upload me-2">
                            <i class="ri-upload-2-line"></i>
                        </label>
                        <input id="file-upload"  name="profile_pic" type="file" onchange="document.getElementById('output').src = window.URL.createObjectURL(this.files[0])"/>
                        <!-- <button class="btn btn-trash-pic"><i class="ri-delete-bin-line"></i></button> -->
                    </div>
                </div>
            </div>


            <div class="col-lg-3">
                <div class="first-input">
                    <label for="">First Name</label>
                    <input type="text"  name="first" class="form-control" required>
                    
                    <label for="">Middle Name</label>
                    <input type="text"  name="middle" class="form-control">
                    
                    <label for="">Last Name</label>
                    <input type="text"  name="last" class="form-control" required>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="first-input">
                    <label for="">Contact No</label>
                    <input type="number"  name="contact_no" class="form-control" min="0" 
                    maxlength="11" 
                    oninput="this.value=this.value.slice(0,this.maxLength)"
                    required>
                    
                    <label for="">Address</label>
                    <input type="text"  name="address" class="form-control" required>
                    
                    <label for="">Email Address</label>
                    <input type="text"  name="email" class="form-control" required>
                    <!-- <br> -->
                    <!-- <input type="submit"  class="btn btn-dark"  value="Update" required> -->
                </div>
                
                <!-- <button type="submit"  class="btn btn-profile-up">Update</button> -->
            </div>
        </div>
    </div>

    <div class="modal-footer border-0">
        <!-- <button type="submit" class="btn btn-primary" value="Add Product"><i class="ri-check-fill"></i>Add Product</button> -->
        <button type="submit" id="submit" name="submit" class="btn btn-primary me-2"><i class="ri-arrow-up-line align-middle me-2 text-end" style="font-size:17px;"></i><span class="align-middle pe-1">Update</span></button>
        <a href="{% url 'admin_site:my_profile' %}" type="submit" id="close-modal" class="btn btn-secondary" data-bs-dismiss="modal" style="font-size: 15px; padding: 5px 13px;"><i class="ri-close-line align-middle me-2 text-end" style="font-size:17px;"></i><span class="align-middle pe-1">Cancel</span></a>
        <!-- <button type="submit" id="close-modal" class="btn btn-secondary" data-bs-dismiss="modal"><i class="ri-close-line align-middle me-2 text-end" style="font-size:17px;"></i><span class="align-middle pe-1">Cancel</span></button> -->
    </div>
    
</form>
{% endif %}